// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEhgrGX-n6uDP7UpCUaqBeZLgXA1MzEew',
    appId: '1:453343817464:web:5c74664c43071d33a0950d',
    messagingSenderId: '453343817464',
    projectId: 'whatsappclone-e29c0',
    authDomain: 'whatsappclone-e29c0.firebaseapp.com',
    storageBucket: 'whatsappclone-e29c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY9HkYqTkzsf4BKvJIMPxaHukfzyKt0oQ',
    appId: '1:453343817464:android:71a7734a9a6d99baa0950d',
    messagingSenderId: '453343817464',
    projectId: 'whatsappclone-e29c0',
    storageBucket: 'whatsappclone-e29c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu5dLDeTP6mKWKSwKWPGve_U3MzPtLvMw',
    appId: '1:453343817464:ios:ee73bb5ac384d845a0950d',
    messagingSenderId: '453343817464',
    projectId: 'whatsappclone-e29c0',
    storageBucket: 'whatsappclone-e29c0.appspot.com',
    iosClientId: '453343817464-sjaet61jvuqmji68anmblms98cd5smj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu5dLDeTP6mKWKSwKWPGve_U3MzPtLvMw',
    appId: '1:453343817464:ios:ee73bb5ac384d845a0950d',
    messagingSenderId: '453343817464',
    projectId: 'whatsappclone-e29c0',
    storageBucket: 'whatsappclone-e29c0.appspot.com',
    iosClientId: '453343817464-sjaet61jvuqmji68anmblms98cd5smj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
